### ISSUE TITLE
Делать редирект, после отправки формы, чтобы защищиться от множественных отправок формы

### ISSUE THREAD

**Issue by php-coder** [flexjoy/spring-discovery#10]
См. https://ru.wikipedia.org/wiki/Post/Redirect/Get

**Comment by flexjoy** [comment]
Слав, я правильно понимаю идею, что после после получения данных (POST) нужно сделать редирект на нужную страницу (GET)? А как передать данные (объект Person  и BindingResult)? Нужно задействовать RedirectAttributes?

**Comment by php-coder** [comment]
Да, правильно. Ты можешь посмотреть как сделано в моем проекте для примера.

В кратце это обычно делается так: в хэндлере для обработки POST-запроса проверяются данные. Если произошла ошибка или еще что-нибудь, то возвращается название вьюхи от страницы с которой пришел запрос (с формой которая). Если ошибок не произошло, то делается редирект на другую страницу. Там отображают то, что только что создали. Т.к. данные обычно сохраняют в БД, а на другой странице их же оттуда вычитывают, то проблем нет. В твоем случае БД еще нет (будет позже) и поэтому я предлагаю пробросить объект с помощью `RedirectAttributes`.
