### ISSUE TITLE
Добавить веб-консоль для просмотра содержимого БД

### ISSUE THREAD

**Issue by php-coder** [flexjoy/spring-discovery#11]
Нужно добавить сервлет для H2, чтобы можно было в БД заглянуть.

Ссылка для примера: https://jira.spring.io/browse/GREENHOUSE-179

**Comment by flexjoy** [comment]
Что то я завяз с этим. Надо же на java config сделать. 
Я сделал класс:

```
@Configuration
public class H2_ServletConfig {

    @Bean
    public WebServlet webServlet() {
        WebServlet servlet = new WebServlet();
        return servlet;
    }
}
```

и пытаюсь его инициализировать:

```
public class WebAppInit extends AbstractAnnotationConfigDispatcherServletInitializer {

    @Override
    protected Class<?>[] getRootConfigClasses() {
        return new Class<?>[] { RootConfig.class };
    }

    @Override
    protected Class<?>[] getServletConfigClasses() {
        return new Class<?>[] { 
                ServletConfig.class, 
                H2_ServletConfig.class 
        };
    }

    @Override
    protected String[] getServletMappings() {
        return new String[] { 
                "/", 
                "/h2/*" 
        };
    }
}
```

я в правильном направлении иду?

**Comment by php-coder** [comment]
Направление, правильное, но раз не работает значит что-то делаешь не совсем так :)

Сам я именно вот так не делал (я настривал либо в `web.xml` либо в коде, но уже для Spring Boot), поэтому 100% сходу не могу дать ответ -- надо пробовать и гуглить.

Вижу, как минимум, два варианта:
- написать класс, который был реализовывал `WebApplicationInitializer` и регистрировал твой сервлет. Насколько помню, все инициализаторы находятся и применяются, так что если у тебя их будет два, это не должно привести к проблемам (но может, если они будут выполняться в разном порядке, в этом случае или надо пробовать пункт 2 или поискать способ указания порядка выполнения, он должен быть)
- вернуться к своей реализации  `WebApplicationInitializer` (которую ты уже делал) и регистрировать в ней свой сервлет. Должно работать.
