### ISSUE TITLE
Не работает i18n в ошибках Spring Security

### ISSUE THREAD

**Issue by flexjoy** [flexjoy/spring-discovery#17]
При ошибках авторизации значение 'SPRING_SECURITY_LAST_EXCEPTION' выводится только в одной локале (RU).

**Comment by php-coder** [comment]
1) Не хватает файла `src/main/resources/SecurityMessages.properties` с английским вариантом сообщения

**Comment by php-coder** [comment]
Проблема в следующем: Spring Security реализован в виде цепочки фильтров, которые исполняются до того как Dispatcher Servlet получит управление. Т.о. выходит, что Spring Security обнаруживает, что идет запрос на аутентификацию, проверяет правильный он или нет, находит, что нет и пытается вернуть ошибку. Чтобы ее локализовать он вызывает `LocaleContextHolder.getLocale()`, но там еще ничего нет и возвращается системная локаль самой JDK. Далее управление передается уже в Dispatcher Servlet, который смотрит на запрос пользователя и вызывает `LocaleContextHolder.setLocale()` с правильной локалью.

Вооружившись этим знанием уже более понятно, что вводить в гугл. Я ввел "spring security expose locale" и набрел на ссылку http://stackoverflow.com/questions/8026320/spring-security-localeresolver где также есть предложение использовать `org.springframework.web.filter.RequestContextFilter` и вызывать его ДО фильтров Spring Security.

Правда, пока что мне не удалось их подружить :)

**Comment by flexjoy** [comment]
Молодец, ты все таки нашел причину. Ну теперь уже будет проще искать решение.

**Comment by php-coder** [comment]
Вызов `RequestContextFilter` перед Spring Security, похоже, что не помогает..

**Comment by flexjoy** [comment]
Я делал это так:

```
    @Override
    protected Filter[] getServletFilters() {
        return new Filter[] {
                new HiddenHttpMethodFilter(), 
                new RequestContextFilter()
        };
    }
```

тоже ничего не вышло.

**Comment by php-coder** [comment]
Это я еще вчера пробовал, но тогда он оказывается после фильтров Spring Security. Сегодня сделал у себя, чтобы он оказывался до, но это не помогло, т.к. он тоже устанавливает язык в русский.

**Comment by php-coder** [comment]
Удалось исправить в своем приложении! Там надо еще будет нормально код "причесать", но оно хотя бы заработало. Следующий шаг, это разобраться как этот фикс прикрутить к твоему приложению, где нет Spring Boot-а (ну или подождать его появляения :) ).

**Comment by flexjoy** [comment]
О, супер! Ты крут! :) Ты мне скинь ссылку на гитхаб как ты реализовал это - я подумаю, как сделать у себя.

**Comment by php-coder** [comment]
Я пока не коммитил, т.к. код надо "причесать" и комментарии добавить, но концепт вот такой:

``` java
    @Bean
    public FilterRegistrationBean getRequestContextFilter() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new FixLocaleFilter());
        registration.setOrder(Ordered.HIGHEST_PRECEDENCE);
        return registration;
    }

    private class FixLocaleFilter implements Filter {
        private SessionLocaleResolver localeResolver = new SessionLocaleResolver();

        private FixLocaleFilter() {
            // TODO: get from context
            this.localeResolver = new SessionLocaleResolver();
            this.localeResolver.setDefaultLocale(Locale.ENGLISH);
        }

        @Override
        public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain) throws IOException, ServletException {

            try {
                LocaleContext localeContext = this.localeResolver.resolveLocaleContext((javax.servlet.http.HttpServletRequest) request);
                if (localeContext != null) {
                    LocaleContextHolder.setLocaleContext(localeContext);
                }
            } catch (Exception e) {
                // TODO: improve logging
                System.out.println(e);
            }

            filterChain.doFilter(request, response);
        }

        @Override
        public void init(FilterConfig filterConfig) throws ServletException {
        }

        @Override
        public void destroy() {
        }
    }
```
