### ISSUE TITLE
Админу невидны ссылки для удаления/редактирования

### ISSUE THREAD

**Issue by php-coder** [flexjoy/spring-discovery#18]

**Comment by flexjoy** [comment]
Этого не может быть. Видны же:
![image](https://cloud.githubusercontent.com/assets/13660819/10051474/59197bda-622a-11e5-8514-1508d3891465.png)
Что не так?

**Comment by php-coder** [comment]
Не знаю, у меня вот так:

![personkeeper](https://cloud.githubusercontent.com/assets/87088/10051563/db322bb2-622a-11e5-9b65-de16bf320e32.png)

**Comment by php-coder** [comment]
А, я понял. Это мы о разных страницах говорим. Я про ту, что появляется сразу после создания.

**Comment by flexjoy** [comment]
Да, ссылки удаления/редактирования только на странице с таблицей. Не верно сделал?

**Comment by php-coder** [comment]
Не знаю, постановки не было :) Можешь либо добавить, либо как хочешь :)

**Comment by flexjoy** [comment]
Ок. Добавлю.
