### ISSUE TITLE
Обновить Servlet API до 3 версии

### ISSUE THREAD

**Issue by php-coder** [flexjoy/spring-discovery#6]
Сейчас в проекте версия 2.5 Лучше сразу обновить до, хотя бы, 3.0 в т.ч. и потому что свежий Spring хочет версию по свежее.

**Comment by flexjoy** [comment]
Обновил до 3.0-alpha-1.
Хотел в комменте написать Fix #5 #6 - думал закроет и #6 тикет тоже, а не сработало.
